window.ZAFAA_MENU = [
  {
    "category": "Bowl",
    "subcategory": "Bowl",
    "name": "Zafaa Special Rice Bowl",
    "item_id": "799770203",
    "variant_id": "1066730246",
    "price": 199,
    "dietary": "veg",
    "description": "Chef special rice bowl with salad.",
    "gst_type": "services",
    "gst": 5,
    "tags": "veg, chef-special, services",
    "image": null
  },
  {
    "category": "Meals",
    "subcategory": "Meals",
    "name": "Jeera Rice Meal",
    "item_id": "799770204",
    "variant_id": "1066730247",
    "price": 199,
    "dietary": "veg",
    "description": "Jeera rice with seasonal vegetable curry.",
    "gst_type": "services",
    "gst": 5,
    "tags": "veg, seasonal, services",
    "image": "Jeera Rice.jpeg"
  },
  {
    "category": "Meals",
    "subcategory": "Meals",
    "name": "Rajma Chawal",
    "item_id": "799770207",
    "variant_id": "1066730250",
    "price": 199,
    "dietary": "veg",
    "description": "Homemade rajma served with steamed rice.",
    "gst_type": "services",
    "gst": 5,
    "tags": "veg, services",
    "image": "Rajma Chawal.jpeg"
  },
  {
    "category": "Meals",
    "subcategory": "Meals",
    "name": "Chole Chawal",
    "item_id": "799770208",
    "variant_id": "1066730251",
    "price": 199,
    "dietary": "veg",
    "description": "Punjabi chole served with basmati rice.",
    "gst_type": "services",
    "gst": 5,
    "tags": "veg, services",
    "image": "Chole Chawal.jpeg"
  },
  {
    "category": "Meals",
    "subcategory": "Meals",
    "name": "Kadhi Chawal",
    "item_id": "799770209",
    "variant_id": "1066730252",
    "price": 199,
    "dietary": "veg",
    "description": "Traditional kadhi served with rice.",
    "gst_type": "services",
    "gst": 5,
    "tags": "veg, services",
    "image": "Kadhi Chawal.jpeg"
  },
  {
    "category": "Meals",
    "subcategory": "Meals",
    "name": "Dal Chawal",
    "item_id": "799770210",
    "variant_id": "1066730253",
    "price": 199,
    "dietary": "veg",
    "description": "Yellow dal tadka with steamed rice.",
    "gst_type": "services",
    "gst": 5,
    "tags": "veg, services",
    "image": null
  },
  {
    "category": "Rice",
    "subcategory": "Rice",
    "name": "Veg Pulao",
    "item_id": "799770211",
    "variant_id": "1066730254",
    "price": 199,
    "dietary": "veg",
    "description": "Fresh vegetable pulao with raita.",
    "gst_type": "services",
    "gst": 5,
    "tags": "veg, services",
    "image": null
  },
  {
    "category": "Rice",
    "subcategory": "Rice",
    "name": "Zafaa Special Aloo Tahari",
    "item_id": "799770212",
    "variant_id": "1066730255",
    "price": 149,
    "dietary": "veg",
    "description": "Special homemade aloo tahari rice meal.",
    "gst_type": "services",
    "gst": 5,
    "tags": "veg, chef-special, services",
    "image": "Aloo Tahri.jpeg"
  },
  {
    "category": "Sweet",
    "subcategory": "Sweet",
    "name": "Badam Barfi [100 g]",
    "item_id": "799770213",
    "variant_id": "1066730256",
    "price": 150,
    "dietary": "veg",
    "description": "Almond based traditional sweet.",
    "gst_type": "goods",
    "gst": 5,
    "tags": "veg, dessert, pre-prepared, non-refundable, goods, category-slab-1, sf-mithai",
    "image": "Badam Barfi.jpeg"
  },
  {
    "category": "Beverages",
    "subcategory": "Beverages",
    "name": "Aam ka Panna",
    "item_id": "799770214",
    "variant_id": "1066730257",
    "price": 149,
    "dietary": "veg",
    "description": "Traditional raw mango summer beverage.",
    "gst_type": "services",
    "gst": 5,
    "tags": "veg, services",
    "image": "Aam Ka Panna.jpeg"
  },
  {
    "category": "Beverages",
    "subcategory": "Beverages",
    "name": "Pudina ka Pani",
    "item_id": "799770215",
    "variant_id": "1066730258",
    "price": 149,
    "dietary": "veg",
    "description": "Refreshing mint beverage.",
    "gst_type": "services",
    "gst": 5,
    "tags": "veg, services",
    "image": "Pudina Ka Pani.jpeg"
  },
  {
    "category": "Beverages",
    "subcategory": "Beverages",
    "name": "Sweet Lassi",
    "item_id": "799770216",
    "variant_id": "1066730259",
    "price": 145,
    "dietary": "veg",
    "description": "Sweet yogurt based beverage.",
    "gst_type": "services",
    "gst": 5,
    "tags": "veg, services, sf-not-vegan",
    "image": "Sweet Lassi.jpeg"
  },
  {
    "category": "Beverages",
    "subcategory": "Beverages",
    "name": "Salted Lassi",
    "item_id": "799770217",
    "variant_id": "1066730260",
    "price": 145,
    "dietary": "veg",
    "description": "Salted yogurt based beverage.",
    "gst_type": "services",
    "gst": 5,
    "tags": "veg, services, sf-not-vegan",
    "image": "Salted Lassi.jpeg"
  },
  {
    "category": "Indian Main Course",
    "subcategory": "Dal, Rajma & Chole",
    "name": "Rajma",
    "item_id": "803035773",
    "variant_id": "1070839141",
    "price": 149,
    "dietary": "veg",
    "description": "Slow cooked kidney beans simmered in a rich tomato-onion gravy with authentic North Indian spices.",
    "gst_type": "services",
    "gst": 5,
    "tags": "veg, services",
    "image": "Rajma Chawal.jpeg"
  },
  {
    "category": "Indian Main Course",
    "subcategory": "Dal, Rajma & Chole",
    "name": "Kadhi",
    "item_id": "803036072",
    "variant_id": "1070839470",
    "price": 149,
    "dietary": "veg",
    "description": "Traditional Punjabi style kadhi made with creamy yogurt and gram flour, delicately spiced and topped with an aromatic tempering.",
    "gst_type": "goods",
    "gst": 5,
    "tags": "veg, goods",
    "image": "Kadhi Chawal.jpeg"
  },
  {
    "category": "Indian Main Course",
    "subcategory": "Dal, Rajma & Chole",
    "name": "Chole",
    "item_id": "803036086",
    "variant_id": "1070839498",
    "price": 149,
    "dietary": "veg",
    "description": "Authentic Punjabi style chickpeas slow cooked in a rich onion-tomato gravy with traditional Indian spices.",
    "gst_type": "services",
    "gst": 5,
    "tags": "veg, services",
    "image": "Chole Chawal.jpeg"
  },
  {
    "category": "Breakfast",
    "subcategory": "Breakfast",
    "name": "Boiled Egg [4 Eggs]",
    "item_id": "804006182",
    "variant_id": "1072050690",
    "price": 89,
    "dietary": "egg",
    "description": "Perfectly boiled eggs, lightly salted, ideal for a simple protein-rich snack or side.",
    "gst_type": "services",
    "gst": 5,
    "tags": "egg, services",
    "image": null
  },
  {
    "category": "Breakfast",
    "subcategory": "Breakfast",
    "name": "Omelette with Toast",
    "item_id": "804006215",
    "variant_id": "1072050727",
    "price": 99,
    "dietary": "egg",
    "description": "Lightly spiced 2-egg omelette served with toasted bread and sauces for a simple, filling meal.",
    "gst_type": "services",
    "gst": 5,
    "tags": "egg, services, sf-spicy",
    "image": null
  },
  {
    "category": "Breakfast",
    "subcategory": "Breakfast",
    "name": "Butter Omelette with Toast",
    "item_id": "804006217",
    "variant_id": "1072050729",
    "price": 125,
    "dietary": "egg",
    "description": "Fluffy 2-egg butter omelette served with toasted bread and sauces for a rich, homestyle meal.",
    "gst_type": "services",
    "gst": 5,
    "tags": "egg, services",
    "image": null
  },
  {
    "category": "Breakfast",
    "subcategory": "Breakfast",
    "name": "Desi Ghee Omelette with Toast",
    "item_id": "804006218",
    "variant_id": "1072050730",
    "price": 149,
    "dietary": "egg",
    "description": "Traditional desi ghee omelette made with 2 eggs, served with toasted bread and sauces.",
    "gst_type": "services",
    "gst": 5,
    "tags": "egg, services",
    "image": null
  },
  {
    "category": "Meals Combos",
    "subcategory": "Meals Combos",
    "name": "Rajma Chawal Combo with Sweet Lassi",
    "item_id": "804400591",
    "variant_id": "1072581527",
    "price": 250,
    "dietary": "veg",
    "description": "Homestyle rajma chawal served with a chilled sweet lassi, a complete single-serve combo.",
    "gst_type": "services",
    "gst": 5,
    "tags": "veg, services, sf-not-vegan",
    "image": null
  },
  {
    "category": "Meals Combos",
    "subcategory": "Meals Combos",
    "name": "Rajma Chawal Combo with Pudina Pani",
    "item_id": "804400609",
    "variant_id": "1072581545",
    "price": 250,
    "dietary": "veg",
    "description": "Homestyle rajma chawal paired with refreshing pudina pani.",
    "gst_type": "services",
    "gst": 5,
    "tags": "veg, services",
    "image": null
  },
  {
    "category": "Meals Combos",
    "subcategory": "Meals Combos",
    "name": "Kadhi Chawal Combo with Aam Panna",
    "item_id": "804400627",
    "variant_id": "1072581566",
    "price": 250,
    "dietary": "veg",
    "description": "Tangy kadhi chawal served with chilled aam ka panna.",
    "gst_type": "services",
    "gst": 5,
    "tags": "veg, services",
    "image": null
  },
  {
    "category": "Meals Combos",
    "subcategory": "Meals Combos",
    "name": "Aloo Tahari Combo with Sweet Lassi",
    "item_id": "804400628",
    "variant_id": "1072581567",
    "price": 250,
    "dietary": "veg",
    "description": "Flavourful aloo tahari rice served with chilled sweet lassi.",
    "gst_type": "services",
    "gst": 5,
    "tags": "veg, services, sf-not-vegan",
    "image": null
  },
  {
    "category": "Meals Combos",
    "subcategory": "Meals Combos",
    "name": "Aloo Tahari Combo with Aam Panna",
    "item_id": "804400629",
    "variant_id": "1072581568",
    "price": 250,
    "dietary": "veg",
    "description": "Flavourful aloo tahari rice paired with chilled aam ka panna.",
    "gst_type": "services",
    "gst": 5,
    "tags": "veg, services",
    "image": null
  },
  {
    "category": "Meals Combos",
    "subcategory": "Meals Combos",
    "name": "Aloo Tahari Combo with Pudina Pani",
    "item_id": "804400636",
    "variant_id": "1072581580",
    "price": 250,
    "dietary": "veg",
    "description": "Flavourful aloo tahari rice served with a glass of pudina pani.",
    "gst_type": "services",
    "gst": 5,
    "tags": "veg, services",
    "image": null
  },
  {
    "category": "Beverages",
    "subcategory": "Beverages",
    "name": "Cold Coffee",
    "item_id": "804404333",
    "variant_id": "1072586377",
    "price": 149,
    "dietary": "veg",
    "description": "Strong café-style cold coffee with chilled milk, sweetened with honey.",
    "gst_type": "services",
    "gst": 5,
    "tags": "veg, services, sf-not-vegan",
    "image": null
  },
  {
    "category": "Beverages",
    "subcategory": "Beverages",
    "name": "Banana Shake",
    "item_id": "804404334",
    "variant_id": "1072586378",
    "price": 149,
    "dietary": "veg",
    "description": "Thick banana milkshake made with ripe banana, chilled milk and honey.",
    "gst_type": "services",
    "gst": 5,
    "tags": "veg, services, sf-not-vegan",
    "image": null
  },
  {
    "category": "Beverages",
    "subcategory": "Beverages",
    "name": "Kit Kat Shake",
    "item_id": "804404335",
    "variant_id": "1072586379",
    "price": 149,
    "dietary": "veg",
    "description": "Chocolate milkshake blended with Kit Kat pieces, chilled milk and honey.",
    "gst_type": "services",
    "gst": 5,
    "tags": "veg, services, sf-not-vegan",
    "image": null
  },
  {
    "category": "Beverages",
    "subcategory": "Beverages",
    "name": "Oreo Shake",
    "item_id": "804404385",
    "variant_id": "1072586429",
    "price": 149,
    "dietary": "veg",
    "description": "Rich cookies-and-cream shake made with Oreo biscuits, chilled milk and honey.",
    "gst_type": "services",
    "gst": 5,
    "tags": "veg, services, sf-not-vegan",
    "image": null
  },
  {
    "category": "Beverages",
    "subcategory": "Beverages",
    "name": "Bournvita Milk",
    "item_id": "804404396",
    "variant_id": "1072586440",
    "price": 149,
    "dietary": "veg",
    "description": "Comforting malt-flavoured milk beverage made with Bournvita, fresh milk and honey.",
    "gst_type": "services",
    "gst": 5,
    "tags": "veg, services, sf-not-vegan",
    "image": null
  },
  {
    "category": "Beverages",
    "subcategory": "Beverages",
    "name": "Mango Shake",
    "item_id": "804404397",
    "variant_id": "1072586441",
    "price": 149,
    "dietary": "veg",
    "description": "Thick mango milkshake made with real mango pulp, chilled milk and honey.",
    "gst_type": "services",
    "gst": 5,
    "tags": "veg, services, sf-not-vegan",
    "image": null
  },
  {
    "category": "Beverages",
    "subcategory": "Beverages",
    "name": "Haldi Wala Milk",
    "item_id": "804404398",
    "variant_id": "1072586442",
    "price": 149,
    "dietary": "veg",
    "description": "Traditional turmeric milk made with haldi, fresh milk and honey.",
    "gst_type": "services",
    "gst": 5,
    "tags": "veg, services, sf-not-vegan",
    "image": null
  },
  {
    "category": "Rice",
    "subcategory": "Rice",
    "name": "Homemade Fried Rice",
    "item_id": "805260151",
    "variant_id": "1073711170",
    "price": 149,
    "dietary": "veg",
    "description": "Homestyle veg fried rice with fluffy rice, mixed vegetables and aromatic spices.",
    "gst_type": "services",
    "gst": 5,
    "tags": "veg, services",
    "image": null
  }
];
